version: '2'

services:

  master:
#    build: .
    image: hri/ros:ros-tutorials
    container_name: master
    command:
      - roscore

  talker:
#    build: .
    image: hri/ros:ros-tutorials
    container_name: talker
    environment:
      - "ROS_HOSTNAME=talker"
      - "ROS_MASTER_URI=http://master:11311"
    command: rosrun roscpp_tutorials talker

  listener:
#    build: .
    image: hri/ros:ros-tutorials
    container_name: listener
    environment:
      - "ROS_HOSTNAME=listener"
      - "ROS_MASTER_URI=http://master:11311"
    command: rosrun roscpp_tutorials listener
